"""empty message

Revision ID: 79d7be499fd2
Revises: 3c541b4e9ac1
Create Date: 2021-05-04 22:32:12.175287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d7be499fd2'
down_revision = '3c541b4e9ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('note', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_note'), 'user', ['note'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_note'), table_name='user')
    op.drop_column('user', 'note')
    # ### end Alembic commands ###
